### ISSUE TITLE
Экран балансов: На экране после "посмотреть всё в USD" переделать кнопку "закрыть" в кнопку "посмотреть в другой валюте"

### ISSUE THREAD

**Issue by iksanov** [sotabots/Billy-webapp#10]
(очень хотел вернуться назад, но не мог и бесился)

**Comment by masguit42** [comment]
Наверное кнопку назад надо переработать. Изначально предлагалось чтобы вместо закрыть можно было выбрать другую валюту, в которой хочется посмотреть
