### ISSUE TITLE
Не разрешать подтверждать транзы после конца лимитов (из разных мест на фронте)

### ISSUE THREAD

**Issue by iksanov** [sotabots/Billy-webapp#16]
Не разрешать подтверждать транзакции из списка транз, если закончился баланс вводов
Именно не просто вырубить полностью подтверждение всех неподтвержденных транзакций
А оставить возможность подтверждать неподтвержденные старые транзы, введенные до окончания лимита
А введеные после лимита - не давать подтверждать 
При попытке это сделать - показывать пейвол и сверху него попап "вы превысили лимит" (описание попапа в соседней задаче: https://github.com/sotabots/Billy-webapp/issues/15)

а еще давай не будем давать подтверждать для случая, когда is_shares_determined=false (мы не смогли сразу точно распознать и не показываем кнопку "все так", а показываем кнопку "проверить") 
И по нажатию на "проверить" чел правит транзу и нажимает "добавить"
В этот момент нужно проверить, не кончились ли лимиты
И если кончились и подтверждать нельзя, то тоже кидаем на пейвол с комментом "вы вышли за лимит"

**Comment by iower** [comment]
> а еще давай не будем давать подтверждать для случая, когда is_shares_determined=false (мы не смогли сразу точно распознать и не показываем кнопку "все так", а показываем кнопку "проверить")
> И по нажатию на "проверить" чел правит транзу и нажимает "добавить"
> В этот момент нужно проверить, не кончились ли лимиты
> И если кончились и подтверждать нельзя, то тоже кидаем на пейвол с комментом "вы вышли за лимит"

Это логика бэка, уже поддержал @masguit42
