### ISSUE TITLE
Добавить параметры в событии send_transaction_web

### ISSUE THREAD

**Issue by iksanov** [sotabots/Billy-webapp#17]
можем еще плз передавать в событии send_transaction_web параметр is_voice=true/false? (is_voice = true - это для и голосового, и текстового ввода)

И еще is_edited=true/false туда же

**Comment by masguit42** [comment]
`is_edited = is_confirmed` для транзакции

**Comment by iksanov** [comment]
Коммент к тому, как сейчас это работает по результату этой задачи:
1/ Чел записал войс. Вместо "всё так", нажал "проверить" и открыл вебвью.
2/ Не стал подтверждать транзу из вебвью и просто вышел
3/ В этот момент у транзы is_confirmed == false
4/ Дальше чел открывает вебвью, делает правки и нажимает "сохранить транзу". Отправляется ивент send_transaction_web с параметром is_edited == false.
5/ У транзы становится is_confirmed == true.
6/ Чел заходит еще раз в вебвью и нажимает "сохранить транзу". Отправляется ивент send_transaction_web с параметром is_edited == true.
